package spring.partie6.persistence.entities;// default package
// Generated 5 sept. 2021 19:22:55 by Hibernate Tools 6.0.0.Alpha5


import javax.persistence.*;
import java.util.Date;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "action"
        , schema = "public"
)
public class Action implements java.io.Serializable {


    private int id;
    private ApplicationUser applicationUser;
    @Column(name = "date_action")
    public Date getDateAction() {
        return dateAction;
    }

    public void setDateAction(Date dateAction) {
        this.dateAction = dateAction;
    }
    @Column(name = "commentaire")
    public String getCommentaire() {
        return commentaire;
    }

    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    public Action(ApplicationUser applicationUser, Date dateAction, String commentaire) {
        this.applicationUser = applicationUser;
        this.dateAction = dateAction;
        this.commentaire = commentaire;
    }

    private Date dateAction;

    private String commentaire;

    public Action() {
    }

    public Action(int id, ApplicationUser applicationUser) {
        this.applicationUser = applicationUser;
    }

    @Id  @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_user", insertable = false, updatable = false)
    public ApplicationUser getApplicationUser() {
        return this.applicationUser;
    }

    public void setApplicationUser(ApplicationUser applicationUser) {
        this.applicationUser = applicationUser;
    }


}


