package spring.partie6.persistence.entities;// default package
// Generated Sep 4, 2021 3:10:07 PM by Hibernate Tools 6.0.0.Alpha5


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name="ACTION"
    ,schema="PUBLIC"
    ,catalog="H2_DATABASE_LIBRAIRE_AVEC_SECURITY"
)
public class Action  implements java.io.Serializable {


     private int id;
     private User user;
     private String commentaire;
     private Date dateAction;

    public Action() {
    }

	
    public Action(int id, User user, Date dateAction) {
        this.id = id;
        this.user = user;
        this.dateAction = dateAction;
    }
    public Action(int id, User user, String commentaire, Date dateAction) {
       this.id = id;
       this.user = user;
       this.commentaire = commentaire;
       this.dateAction = dateAction;
    }
   
     @Id
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_USER", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="COMMENTAIRE", length=64)
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_ACTION", nullable=false, length=10)
    public Date getDateAction() {
        return this.dateAction;
    }
    
    public void setDateAction(Date dateAction) {
        this.dateAction = dateAction;
    }




}


