package spring.partie6.persistence.entities;// default package
// Generated 5 sept. 2021 20:06:27 by Hibernate Tools 6.0.0.Alpha5


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationUser generated by hbm2java
 */
@Entity
@Table(name = "application_user"
        , schema = "public"
)
public class ApplicationUser implements java.io.Serializable {


    private int id;
    private String username;
    private String nom;
    private String password;
    private String mail;
    private boolean actif;
    private Set<Action> actions = new HashSet<>(0);
    private Set<UserRole>  userRoles = new HashSet<>(0);
    private Set<Livre> livres = new HashSet<>(0);

    public ApplicationUser() {
    }


    public ApplicationUser(String username, String nom, String password, String mail, boolean actif) {
        this.username = username;
        this.nom = nom;
        this.password = password;
        this.mail = mail;
        this.actif = actif;
    }

    public ApplicationUser(String username, String nom, String password, String mail, boolean actif, Set<Action> actions, Set<UserRole>  userRoles, Set<Livre> livres) {
        this.username = username;
        this.nom = nom;
        this.password = password;
        this.mail = mail;
        this.actif = actif;
        this.actions = actions;
        this.userRoles = userRoles;
        this.livres = livres;
    }

    @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @Column(name = "username", nullable = false, length = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }


    @Column(name = "nom", nullable = false, length = 64)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }


    @Column(name = "password", nullable = false, length = 64)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    @Column(name = "mail", nullable = false, length = 64)
    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }


    @Column(name = "actif", nullable = false)
    public boolean isActif() {
        return this.actif;
    }

    public void setActif(boolean actif) {
        this.actif = actif;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "applicationUser")
    public Set<Action> getActions() {
        return this.actions;
    }

    public void setActions(Set<Action> actions) {
        this.actions = actions;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "applicationUser")
    public Set<UserRole>  getUserRoles() {
        return this.userRoles;
    }

    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }


    public void setLivres(Set<Livre> livres) {
        this.livres = livres;
    }

    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL})
    @JoinTable(
            name = "user_livre",
            joinColumns = @JoinColumn(name = "ID_USER"),
            inverseJoinColumns = @JoinColumn(name = "ID_LIVRE"))
    public Set<Livre> getLivres() {
        return this.livres;
    }
}


