package spring.partie6.persistence.entities;// default package
// Generated 5 sept. 2021 20:06:27 by Hibernate Tools 6.0.0.Alpha5


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Auteur generated by hbm2java
 */
@Entity
@Table(name = "auteur"
        , schema = "public"
)
public class Auteur implements java.io.Serializable {


    private int id;
    private String nom;
    private String prenom;
    private Set<Livre> livres = new HashSet(0);

    public Auteur() {
    }


    public Auteur( String nom,String prenom) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
    }

    public Auteur( String nom, String prenom, Set<Livre>  livres) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.livres = livres;
    }

    @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @Column(name = "nom", nullable = false, length = 64)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }


    @Column(name = "prenom", length = 64)
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "auteur")
    public Set<Livre>  getLivres() {
        return this.livres;
    }

    public void setLivres(Set<Livre>  livres) {
        this.livres = livres;
    }


}


