package spring.partie6.persistence.entities;// default package
// Generated 5 sept. 2021 20:06:27 by Hibernate Tools 6.0.0.Alpha5


import javax.persistence.*;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Livre generated by hbm2java
 */
@Entity
@Table(name = "livre"
        , schema = "public"
)
public class Livre implements java.io.Serializable {


    private int id;
    private Profil profil;
    private Stock stock;
    private Auteur auteur;
    private String nom;
    private String langue;
    private int prix;
    private Set<ApplicationUser> users = new HashSet<>(0);

    public Livre() {
    }


    public Livre(Profil profil, Stock stock, Auteur auteur, String nom, int prix) {
        this.id = id;
        this.profil = profil;
        this.stock = stock;
        this.auteur = auteur;
        this.nom = nom;
        this.prix = prix;
    }

    public Livre( Profil profil, Stock stock, Auteur auteur, String nom, String langue, int prix, Set userLivres) {
        this.id = id;
        this.profil = profil;
        this.stock = stock;
        this.auteur = auteur;
        this.nom = nom;
        this.langue = langue;
        this.prix = prix;
    }

    @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
    @JoinColumn(name = "id_profil", nullable = false)
    public Profil getProfil() {
        return this.profil;
    }

    public void setProfil(Profil profil) {
        this.profil = profil;
    }

    @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
    @JoinColumn(name = "id_stock", nullable = false)
    public Stock getStock() {
        return this.stock;
    }

    public void setStock(Stock stock) {
        this.stock = stock;
    }

    @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
    @JoinColumn(name = "id_auteur", nullable = false)
    public Auteur getAuteur() {
        return this.auteur;
    }

    public void setAuteur(Auteur auteur) {
        this.auteur = auteur;
    }


    @Column(name = "nom", nullable = false, unique = true,length = 64)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }


    @Column(name = "langue", length = 64)
    public String getLangue() {
        return this.langue;
    }

    public void setLangue(String langue) {
        this.langue = langue;
    }


    @Column(name = "prix", nullable = false)
    public int getPrix() {
        return this.prix;
    }

    public void setPrix(int prix) {
        this.prix = prix;
    }

    @ManyToMany(fetch = FetchType.EAGER, mappedBy = "livres")
    public Set<ApplicationUser> users() {
        return this.users;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Livre livre = (Livre) o;
        return id == livre.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}


