package spring.partie6.persistence.entities;// default package
// Generated 5 sept. 2021 20:06:27 by Hibernate Tools 6.0.0.Alpha5


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "profil"
        , schema = "public"
)
public class Profil implements java.io.Serializable {


    private int id;
    private Date datePublication;
    private String genre;
    private Set<Livre> livres = new HashSet(0);

    public Profil() {
    }


    public Profil(Date datePublication, String genre, Set<Livre> livres) {
        this.datePublication = datePublication;
        this.genre = genre;
        this.livres = livres;
    }

    public Profil(Date datePublication, String genre) {
        this.datePublication = datePublication;
        this.genre = genre;
    }

    @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_publication", length = 13)
    public Date getDatePublication() {
        return this.datePublication;
    }

    public void setDatePublication(Date datePublication) {
        this.datePublication = datePublication;
    }


    @Column(name = "genre", length = 64)
    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "profil")
    public Set<Livre> getLivres() {
        return this.livres;
    }

    public void setLivres(Set<Livre> livres) {
        this.livres = livres;
    }


}


