package spring.partie6.persistence.entities;// default package
// Generated Sep 2, 2021 9:48:27 AM by Hibernate Tools 6.0.0.Alpha5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name="PROFIL"
    ,schema="PUBLIC"
    ,catalog="H2_DATABASE_LIBRAIRE"
)
public class Profil  implements java.io.Serializable {


     private int id;
     private Date datePublication;
     private String genre;

    public Profil() {
    }

	
    public Profil(int id) {
        this.id = id;
    }
    public Profil(int id, Date datePublication, String genre) {
       this.id = id;
       this.datePublication = datePublication;
       this.genre = genre;
    }
   
    @Id
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_PUBLICATION", length=10)
    public Date getDatePublication() {
        return this.datePublication;
    }
    
    public void setDatePublication(Date datePublication) {
        this.datePublication = datePublication;
    }

    
    @Column(name="GENRE", length=64)
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }





}


