package spring.partie6.persistence.entities;// default package
// Generated Sep 3, 2021 4:22:08 PM by Hibernate Tools 6.0.0.Alpha5


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="ROLE"
    ,schema="PUBLIC"
    ,catalog="H2_DATABASE_LIBRAIRE_AVEC_SECURITY"
)
public class Role  implements java.io.Serializable {


     private int id;
     private String nom;
     private String description;
     private Set<UserRole> userRoles = new HashSet(0);

    public Role() {
    }

	
    public Role(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Role(int id, String nom, String description, Set userRoles) {
       this.id = id;
       this.nom = nom;
       this.description = description;
       this.userRoles = userRoles;
    }
   
     @Id
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NOM", nullable=false, length=64)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="role")
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }




}


