package spring.partie6.persistence.entities;// default package
// Generated Sep 4, 2021 10:24:16 AM by Hibernate Tools 6.0.0.Alpha5


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name="STOCK"
    ,schema="PUBLIC"
    ,catalog="H2_DATABASE_LIBRAIRE_AVEC_SECURITY"
)
public class Stock  implements java.io.Serializable {


     private int id;
     private int nombre;
     private Set<Livre> livres = new HashSet<>(0);

    public Stock() {
    }

	
    public Stock(int id, int nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Stock(int id, int nombre, Set livres) {
       this.id = id;
       this.nombre = nombre;
       this.livres = livres;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NOMBRE", nullable=false)
    public int getNombre() {
        return this.nombre;
    }
    
    public void setNombre(int nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="stock")
    public Set<Livre> getLivres() {
        return this.livres;
    }
    
    public void setLivres(Set<Livre>  livres) {
        this.livres = livres;
    }




}


