package spring.partie6.persistence.entities;// default package
// Generated 5 sept. 2021 20:06:27 by Hibernate Tools 6.0.0.Alpha5


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock"
        , schema = "public"
)
public class Stock implements java.io.Serializable {


    private int id;
    private int nombre;
    private Set<Livre> livres = new HashSet(0);

    public Stock() {
    }


    public Stock( int nombre) {
        this.nombre = nombre;
    }

    public Stock(int nombre, Set<Livre> livres) {
        this.nombre = nombre;
        this.livres = livres;
    }

    @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @Column(name = "nombre", nullable = false)
    public int getNombre() {
        return this.nombre;
    }

    public void setNombre(int nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "stock")
    public Set<Livre> getLivres() {
        return this.livres;
    }

    public void setLivres(Set<Livre> livres) {
        this.livres = livres;
    }


}


