package spring.partie6.persistence.entities;// default package
// Generated Sep 4, 2021 8:13:52 AM by Hibernate Tools 6.0.0.Alpha5


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserLivre generated by hbm2java
 */
@Entity
@Table(name="USER_LIVRE"
    ,schema="PUBLIC"
    ,catalog="H2_DATABASE_LIBRAIRE_AVEC_SECURITY"
)
public class UserLivre  implements java.io.Serializable {


     private UserLivreId id;
     private Livre livre;
     private User user;

    public UserLivre() {
    }

    public UserLivre(UserLivreId id, Livre livre, User user) {
       this.id = id;
       this.livre = livre;
       this.user = user;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idLivre", column=@Column(name="ID_LIVRE", nullable=false) ), 
        @AttributeOverride(name="idUser", column=@Column(name="ID_USER", nullable=false) ) } )
    public UserLivreId getId() {
        return this.id;
    }
    
    public void setId(UserLivreId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_LIVRE", nullable=false, insertable=false, updatable=false)
    public Livre getLivre() {
        return this.livre;
    }
    
    public void setLivre(Livre livre) {
        this.livre = livre;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_USER", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


