package spring.partie6.persistence.entities;// default package
// Generated Sep 4, 2021 8:13:52 AM by Hibernate Tools 6.0.0.Alpha5


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "USER"
        , schema = "PUBLIC"
        , catalog = "H2_DATABASE_LIBRAIRE_AVEC_SECURITY"
)
public class User implements java.io.Serializable {


    private int id;
    private String username;
    private String nom;
    private String prenom;
    private String password;
    private String mail;
    private boolean actif;



    private Set<Livre> livres = new HashSet<>(0);
    private Set<UserRole> userRoles = new HashSet<>(0);

    public User() {
    }


    public User(int id, String username, String nom, String prenom, String password, String mail, boolean actif) {
        this.id = id;
        this.username = username;
        this.nom = nom;
        this.prenom = prenom;
        this.password = password;
        this.mail = mail;
        this.actif = actif;
    }

    public User(int id, String username, String nom, String prenom, String password, String mail, boolean actif, Set<Livre> userLivres, Set<UserRole> userRoles) {
        this.id = id;
        this.username = username;
        this.nom = nom;
        this.prenom = prenom;
        this.password = password;
        this.mail = mail;
        this.actif = actif;
        this.livres = userLivres;
        this.userRoles = userRoles;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @Column(name = "USERNAME", nullable = false, length = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }


    @Column(name = "NOM", nullable = false, length = 64)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }


    @Column(name = "PRENOM", nullable = false, length = 64)
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }


    @Column(name = "PASSWORD", nullable = false, length = 64)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    @Column(name = "MAIL", nullable = false, length = 64)
    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }


    @Column(name = "ACTIF", nullable = false)
    public boolean isActif() {
        return this.actif;
    }

    public void setActif(boolean actif) {
        this.actif = actif;
    }

    @ManyToMany(fetch = FetchType.EAGER,cascade = {CascadeType.ALL})
    @JoinTable(
            name = "user_livre",
            joinColumns = @JoinColumn(name = "ID_USER"),
            inverseJoinColumns = @JoinColumn(name = "ID_LIVRE"))
    public Set<Livre> getLivres() {
        return this.livres;
    }

    public void setLivres(Set<Livre> livres) {
        this.livres = livres;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }

    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }


}


