package spring.partie6.persistence.entities;// default package
// Generated 5 sept. 2021 20:06:27 by Hibernate Tools 6.0.0.Alpha5


import javax.persistence.*;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role"
        , schema = "public"
)
public class UserRole implements java.io.Serializable {


    private UserRoleId id;
    private Role role;
    private ApplicationUser applicationUser;

    public UserRole() {
    }


    public UserRole(UserRoleId id) {
        this.id = id;
    }

    public UserRole(UserRoleId id, Role role, ApplicationUser applicationUser) {
        this.id = id;
        this.role = role;
        this.applicationUser = applicationUser;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "idRole", column = @Column(name = "id_role")),
            @AttributeOverride(name = "idUser", column = @Column(name = "id_user"))})
    public UserRoleId getId() {
        return this.id;
    }

    public void setId(UserRoleId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_role", insertable = false, updatable = false)
    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_user", insertable = false, updatable = false)
    public ApplicationUser getApplicationUser() {
        return this.applicationUser;
    }

    public void setApplicationUser(ApplicationUser applicationUser) {
        this.applicationUser = applicationUser;
    }
}


